import {
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  Plus,
  X,
  AlertCircle,
  CheckCircle2,
  Info,
  User,
  Building2,
  FileText,
  Settings,
  LogOut,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Search,
  Upload,
  Download,
  Trash2,
  Edit,
  MoreVertical,
  Calendar,
  Clock,
  Loader2,
  RefreshCcw,
  Filter,
  SlidersHorizontal,
  ArrowUpDown,
  ArrowLeft,
  ArrowRight,
  Home,
  LayoutDashboard,
  Users,
  Bell,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  circle: Circle,
  plus: Plus,
  close: X,
  error: AlertCircle,
  success: CheckCircle2,
  info: Info,
  user: User,
  company: Building2,
  document: FileText,
  settings: Settings,
  logout: LogOut,
  email: Mail,
  password: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  search: Search,
  upload: Upload,
  download: Download,
  delete: Trash2,
  edit: Edit,
  more: MoreVertical,
  calendar: Calendar,
  time: Clock,
  loading: Loader2,
  refresh: RefreshCcw,
  filter: Filter,
  sliders: SlidersHorizontal,
  sort: ArrowUpDown,
  back: ArrowLeft,
  next: ArrowRight,
  home: Home,
  dashboard: LayoutDashboard,
  users: Users,
  notifications: Bell,
} as const; 